# Site settings
title: Day Zero
description: The Beginning.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://nol.ski" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: sxltnolan
twitter: __nolski__
github: nolski

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: nolski #github username
repo: nol.ski #github repository
branch: master #branch
relative_source: ../nol.ski/ #source directory
destination: ../nol.ski-pages/ #destination directory
production_url:  https://nol.ski/
source_url:  https://github.com/nolski/nol.ski #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml